name: dacon
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - ipykernel
  - matplotlib
  - pip
  - pip:
      - opencv-python
      - albumentations
      - torch
      - torchvision
      - transformers
      - wandb
